### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by OptogeneticsandNeuralEngineeringCore** [quanticchaos/OctoPrint-Webcamsb#1]
Thanks for this!

Rotate CW and CCW (with flips) would be nice.

**Comment by quanticchaos** [comment]
Thanks for your feedback, I'll try to add your suggestion in the next release.

**Comment by MrVinyla** [comment]
Would be nice that the image can be rotated 90 degrees  CC and CCW. Thanks

**Comment by snuids** [comment]
This would a marvellous add on to this wonderful plugin.

**Comment by quanticchaos** [comment]
I'm on it, friends. Found some small problems but I hope I can release it the next week or before.

**Comment by quanticchaos** [comment]
Please download the newest version. Fullscreen image of rotated stream still not fully functional.

**Comment by quanticchaos** [comment]
Thanks for the feedback.
