### ISSUE TITLE
Webcamsb ignores Octoprint Webcam Flip settings

### ISSUE THREAD

**Issue by GaryGJR** [quanticchaos/OctoPrint-Webcamsb#12]
Using Raspberry Pi Cam V2, my image naturally comes out upside down - due to the way the camera is mounted..
Under:  OctoPrint Settings - Webcam & Timelapse
To get the video image under the Control tab to look right side up, I use the settings:
       Flip webcam horizontally
       Flip webcam vertically

For Webcamsb, these settings look to be ignored.  So, the image in the sidebar is upside down, while the image under the control tab is right side up.
![Upside down](https://user-images.githubusercontent.com/67721303/86312071-74d24c00-bbe7-11ea-8d4f-22710789c1b1.png)

I appreciate your work.  Thanks.

**Comment by quanticchaos** [comment]
Hello, please try to flip it from the plugin settings.

**Comment by GaryGJR** [comment]
Hi, I've managed to flip it in the octopi conf file.
