### ISSUE TITLE
Image doesn't update

### ISSUE THREAD

**Issue by terryb58** [quanticchaos/OctoPrint-Webcamsb#3]
![Sidebar Camera](https://user-images.githubusercontent.com/9091131/64898285-8ea0a380-d654-11e9-893e-20549a3cb643.png)

**Comment by quanticchaos** [comment]
Can you provide me details on the browser, the kind of camera, and the URL you are using to see If I can reproduce this issue? Does this happen all the time or just when you are in the Control tab?

**Comment by terryb58** [comment]
I'm using Firefox 69.0 64-bit. The camera is a USB camera. It happens all the time whether I'm in the control tab or not. It's as if the image in the sidebar just froze and nothing I've tried will refresh it. I tried clicking on it but it'll just go full screen and when I go back to normal it's still the same.  But I'm having the same problem on a different printer that uses the RPi camera. I'm attaching a screenshot. I'm also attaching a screenshot of my webcam settings.

![WebcamSettings](https://user-images.githubusercontent.com/9091131/64909445-2f857200-d6da-11e9-8c14-3828fca99a50.png)
![Sidebar Camera (X1)](https://user-images.githubusercontent.com/9091131/64909446-2f857200-d6da-11e9-9248-2f865ea9152a.png)



The url is  http://192.168.1.190/webcam/?action=stream. I also use it from outside of my network with the same result. Same stream URL (/webcam/?action=stream).

**Comment by quanticchaos** [comment]
Thanks again for your feedback, I'm very sorry for the inconvenience. May I ask if you have the same issue in another browser? Even though I also use FF 69 64bit, so I don't think it's the browser.  Could you try using only the sidebar stream removing the URL from the webcam conf just to see if it works like that? Unfortunately, I don't have a PI right now so I cannot try to mimic your problem albeit the first people that tried it did use a RPI with a USB cam and did not have your problem. I'm going to get a RPI the next week to try to duplicate this issue.

**Comment by terryb58** [comment]
No inconvenience at all. I didn't get to try it in Chrome before I removed the URL from the webcam config.  It worked fine in Firefox without the webcam URL.  I did reenter the webcam URL before I started my current print because I need it to work in Printoid and I'm not sure that'll work without the webcam URL.  It seems to still be updating now.  Btw, all instances of OctoPrint are 1.3.12rc1.

**Comment by quanticchaos** [comment]
Thanks again. I tried it with the latest Octoprint and that doesn't seem to be the problem. I ordered an RPI 3b+ from Amazon on Saturday but, since I don't live in the US, it'll take a little longer to arrive. BTW Printoid doesn't need you to set the cam in Octoprint, it's set in the app itself (I also use it). As soon as I can find anything I'll report back to you.

**Comment by terryb58** [comment]
I don't remember having to set the camera URL in printoid. But then again it's been a while since I've setup a new printer on Printoid from scratch. Anyway, it works fine now. I don't know what caused it to freeze. Maybe a full Octopi restart was all that was needed and not just OctoPrint.

**Comment by quanticchaos** [comment]
Yes, Printoid comes with the same webcam config as the default one in Octoprint but if you change your Octoprint webcam you'll have to manually change it in Printoid. Anyway, those are good news, it works with both the stream on the side and on the control tab?

**Comment by terryb58** [comment]
I see. Yes, both work in sync now.

**Comment by quanticchaos** [comment]
Ok, thanks again for the feedback, feel free to close the thread.
