### ISSUE TITLE
Auto Collapse Sidebar Webcam

### ISSUE THREAD

**Issue by phcoetzee** [quanticchaos/OctoPrint-Webcamsb#4]
Hi, I have a suggestion. Isn't it possible to have the Sidebar Webcam auto collapse on page load like the Auto Collapse Files Plugin? Then when you want to see the webcam feed you just click on Stream and it unfolds. Thanks.

**Comment by quanticchaos** [comment]
Interesting idea, thanks. I'll try to implement it in next versions. In the meantime, you can use this plugin, It will remember the state of each element of the sidebar. I don't know why they removed it from the repository, It's from jneilliii and I've being using it for a while. You'll have to download the zip file and install it manually with the plugin manager. 
https://github.com/jneilliii/OctoPrint-StatefulSidebar

**Comment by phcoetzee** [comment]
Thank you for the nice plugins you create. Keep it up.

**Comment by quanticchaos** [comment]
Thank you!!
