### ISSUE TITLE
Full Screen Video Doesn't Respect Aspect Ratio

### ISSUE THREAD

**Issue by offroadguy56** [quanticchaos/OctoPrint-Webcamsb#5]
If you resize your window smaller than the length of the video, the video squash and use the aspect ratio of the window instead. 

Here's an example. [https://imgur.com/a/QLZ1zpX](https://imgur.com/a/QLZ1zpX) first noticed this on Android, but it appears it can be recreated on Chrome in Windows 10.

**Comment by quanticchaos** [comment]
Yes it doesn't have an on resize event. But I'll look forward into it.

**Comment by quanticchaos** [comment]
I began trying to create a simple and light plugin. But yeah, I guess that's something I should have thought of when I added the fullscreen functionality

**Comment by offroadguy56** [comment]
Yeah. I'm a huge supporter of K.I.S.S.
I was just a little startled when I opened it on my phone and thought I had broken something on the plugin. 

I'm fine with it staying as is, but other users might not be so lucky and will not be able to resize the window to see proper video. But hey, the default octoprint webcam view is good enough.

**Comment by quanticchaos** [comment]
Don't worry, I agree with you, it's something that has to be fixed.

**Comment by quanticchaos** [comment]
Just updated the script, please check if it's working now.
