### ISSUE TITLE
[Feature Request] Python 3 Compatibility

### ISSUE THREAD

**Issue by jneilliii** [quanticchaos/OctoPrint-Webcamsb#9]
**Is your feature request related to a problem? Please describe.**
Running the latest version of OctoPrint 1.4.0 in a Python 3 environment does not allow for the use of this plugin as it is detected as incompatible.

**Describe the solution you'd like**
The ability to run the plugin in a Python 3 environment.

**Additional context**
Please see [here](https://docs.octoprint.org/en/master/plugins/python3_migration.html) for additional information regarding OctoPrint and Python 3 Migration.

**Comment by quanticchaos** [comment]
Dear jneilliii, thanks for the advice and help, as usual. As soon as I install the environment I will update the plugin. Stay safe.

**Comment by Bootscreen** [comment]
Any News about an update?

**Comment by jneilliii** [comment]
@quanticchaos I've verified compatibility for you and submitted a PR to your repo. You'll just need to merge that in and then submit a PR to plugins.octoprint.org for the updated compatibility flag.

**Comment by quanticchaos** [comment]
Dear jneilliii. I'm very sorry for the delay. I've been like crazy with the quarantine taking care of my father and my family. Thank you very much for your help. I just released the new version with your changes.

**Comment by jneilliii** [comment]
No problem, there's still one more step for full compatibility. You need to update the plugins.octoprint.org md file for your plugin to also publish thre python 3 compatibility. Good luck with your family.

**Comment by quanticchaos** [comment]
Thanks again.
